# Generated by Django 4.2 on 2024-07-12 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoucherTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("currency", models.CharField(choices=[("€", "EUR"), ("$", "USD")])),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buyer", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased"),
                            ("cancelled", "Cancelled"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ]
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vouchers.vouchertemplate",
                    ),
                ),
            ],
        ),
    ]
