# Generated by Django 4.2 on 2024-07-12 19:57

from django.db import migrations


def create_initial_voucher_templates(apps, schema_editor):
    VoucherTemplate = apps.get_model("vouchers", "VoucherTemplate")

    VoucherTemplate.objects.create(
        title="Quantum Cuisine - introductory course",
        description="With this course, you will learn the basics of Quantum Cuisine and how it differs with traditional molecular gastronomy.",
        price=4136,
        currency="EUR",
    )
    VoucherTemplate.objects.create(
        title="Quantum Cuisine - dealing with taste entanglement",
        description="With this advanced course, you will learn how to cook taking into account the taste entanglement and how to manage taste uncertainty with heating wave functions.",
        price=29979,
        currency="EUR",
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0001_create_voucher_models"),
    ]

    operations = [
        migrations.RunPython(create_initial_voucher_templates, reverse_func),
    ]
