# Generated by Django 4.2 on 2024-07-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0002_create_initial_voucher_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="currency",
            field=models.CharField(choices=[("EUR", "€"), ("USD", "$")], default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucher",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucher",
            name="price",
            field=models.IntegerField(default=0, help_text="In minor units"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucher",
            name="title",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("used", "Used"),
                    ("expired", "Expired"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vouchers.vouchertemplate",
            ),
        ),
        migrations.AlterField(
            model_name="vouchertemplate",
            name="currency",
            field=models.CharField(choices=[("EUR", "€"), ("USD", "$")]),
        ),
        migrations.AlterField(
            model_name="vouchertemplate",
            name="price",
            field=models.IntegerField(help_text="In minor units"),
        ),
    ]
